// Gandle word list — add or remove words here to update the puzzle pool.
// All words must be exactly 6 letters, lowercase.
// Words are cycled daily in order, so spread difficulty evenly.

export const GANDLE_WORDS: readonly string[] = [
  'absent', 'accept', 'access', 'accord', 'accuse', 'active', 'actual', 'affect',
  'affirm', 'afraid', 'agency', 'agenda', 'almost', 'always', 'anchor', 'answer',
  'anyone', 'around', 'artist', 'aspect', 'assert', 'assign', 'attack', 'attend',
  'author', 'autumn', 'backed', 'ballot', 'barely', 'battle', 'beauty', 'became',
  'before', 'behalf', 'behind', 'belong', 'better', 'beyond', 'bishop', 'bitter',
  'blazed', 'blight', 'blouse', 'bottle', 'bought', 'bridge', 'broken', 'bronze',
  'budget', 'burden', 'burned', 'butter', 'button', 'called', 'camera', 'cannot',
  'carbon', 'career', 'castle', 'casual', 'caught', 'chance', 'change', 'charge',
  'cherry', 'chosen', 'chrome', 'circle', 'claims', 'clever', 'clover', 'cobalt',
  'coming', 'commit', 'common', 'cookie', 'corner', 'costly', 'county', 'course',
  'cousin', 'create', 'credit', 'crisis', 'damage', 'danger', 'debate', 'decade',
  'decide', 'define', 'demand', 'dental', 'detail', 'detect', 'differ', 'dinner',
  'direct', 'divide', 'dollar', 'domain', 'double', 'driven', 'during', 'earned',
  'easily', 'editor', 'effect', 'either', 'eleven', 'employ', 'energy', 'engine',
  'enough', 'ensure', 'entire', 'escape', 'events', 'except', 'exists', 'expect',
  'expert', 'extend', 'fabled', 'facing', 'factor', 'falcon', 'fallen', 'family',
  'famous', 'farmer', 'faster', 'fellow', 'fender', 'figure', 'finger', 'finish',
  'flight', 'forest', 'formal', 'formed', 'former', 'fought', 'fourth', 'framed',
  'friend', 'frozen', 'future', 'garden', 'gather', 'gender', 'giving', 'global',
  'gloves', 'goblin', 'golden', 'gravel', 'ground', 'growth', 'guests', 'guided',
  'handle', 'happen', 'harbor', 'harder', 'health', 'height', 'helped', 'herald',
  'higher', 'highly', 'holder', 'honest', 'humble', 'hunter', 'impact', 'income',
  'inform', 'inside', 'insect', 'intent', 'invest', 'island', 'issues', 'itself',
  'joined', 'judges', 'jumped', 'jungle', 'junior', 'keeper', 'killer', 'kitten',
  'knight', 'ladder', 'latest', 'launch', 'lessen', 'letter', 'levels', 'lifted',
  'likely', 'listed', 'little', 'locket', 'losing', 'luggage', 'mammal', 'market',
  'master', 'matter', 'meadow', 'member', 'mental', 'method', 'minute', 'mirror',
  'missed', 'modern', 'moment', 'mostly', 'mother', 'motion', 'muddle', 'needle',
  'needed', 'normal', 'notice', 'number', 'object', 'obtain', 'office', 'option',
  'orange', 'others', 'output', 'oyster', 'passed', 'paying', 'pencil', 'period',
  'person', 'pirate', 'places', 'planet', 'plenty', 'police', 'policy', 'public',
  'puzzle', 'rabbit', 'raisin', 'rather', 'reason', 'reform', 'reject', 'remain',
  'remark', 'remote', 'repeat', 'report', 'resign', 'result', 'return', 'reveal',
  'review', 'reward', 'rights', 'rising', 'rocket', 'rubber', 'saddle', 'sailor',
  'salmon', 'sample', 'school', 'search', 'season', 'second', 'secret', 'sector',
  'seeing', 'series', 'shield', 'signal', 'silent', 'silver', 'simple', 'simply',
  'single', 'sister', 'sleeve', 'slight', 'slowly', 'smooth', 'spider', 'spoken',
  'sponge', 'spring', 'stream', 'street', 'strict', 'strike', 'strong', 'struck',
  'stupid', 'sudden', 'suffer', 'summer', 'supply', 'surely', 'switch', 'system',
  'talent', 'target', 'tested', 'thanks', 'theory', 'things', 'though', 'thread',
  'throat', 'throne', 'thrown', 'ticket', 'timber', 'toward', 'trying', 'tunnel',
  'turtle', 'typing', 'unable', 'united', 'unlike', 'update', 'useful', 'utmost',
  'valley', 'values', 'varied', 'velvet', 'verify', 'victim', 'violin', 'vision',
  'wallet', 'walnut', 'wander', 'wanted', 'wealth', 'winner', 'within', 'wonder',
  'worker', 'worthy', 'yellow', 'zipper', 'abrupt', 'adjust', 'admire', 'advert',
  'advice', 'beacon', 'bedded', 'bitter', 'blazer', 'bleach', 'blends', 'blotch',
  'blurry', 'blurts', 'bounty', 'brainy', 'brandy', 'breach', 'breeze', 'bridal',
  'bright', 'brooch', 'bucket', 'buffet', 'bumble', 'bureau', 'bustle', 'candle',
  'canvas', 'cavern', 'cellar', 'cereal', 'chapel', 'chimps', 'clinch', 'clings',
  'cloaks', 'clumps', 'clutch', 'coarse', 'cobble', 'codify', 'cohort', 'comply',
  'confer', 'crafty', 'crayon', 'crease', 'crispy', 'crutch', 'cuddle', 'curfew',
  'dagger', 'dapper', 'daring', 'darken', 'dashed', 'daylight', 'deadly', 'deceit',
  'decode', 'deeply', 'defend', 'defuse', 'delete', 'deluge', 'devour', 'devout',
  'disarm', 'disown', 'dispel', 'distal', 'dither', 'divest', 'donkey', 'doting',
  'drafts', 'draggy', 'dreamy', 'dressy', 'drifts', 'drills', 'drolly', 'dropsy',
  'earthy', 'eddies', 'effigy', 'elapse', 'eluded', 'embark', 'embody', 'embers',
  'emerge', 'empire', 'entrap', 'enrich', 'excels', 'excuse', 'famine', 'farmed',
  'faucet', 'feline', 'fervid', 'festal', 'fetter', 'fickle', 'fierce', 'filter',
  'fizzle', 'flanks', 'flavor', 'flinch', 'floppy', 'flushed', 'fodder', 'foible',
  'fondly', 'forbid', 'foster', 'frenzy', 'frisky', 'frothy', 'fuddle', 'fumble',
  'gamble', 'garlic', 'garner', 'gauche', 'giggle', 'ginger', 'glitch', 'glitzy',
  'gloomy', 'glossy', 'grassy', 'greedy', 'grimly', 'grumpy', 'gusher', 'haggle',
  'hamper', 'haptic', 'hazard', 'holler', 'hornet', 'hubris', 'huddle', 'hustle',
  'ignite', 'impede', 'impose', 'invert', 'jangle', 'jargon', 'jaunty', 'jogger',
  'jostle', 'jumble', 'lament', 'lancer', 'lather', 'lavish', 'lawful', 'leader',
  'leaden', 'lively', 'lizard', 'locker', 'lofted', 'louden', 'lounge', 'lucent',
  'lumber', 'lurked', 'mangle', 'mantle', 'marvel', 'mascot', 'mayhem', 'menace',
  'mingle', 'minted', 'mutter', 'mystic', 'nibble', 'nifty', 'nimble', 'nobles',
  'noodle', 'nudged', 'obscure', 'ordeal', 'overdo', 'paddle', 'pander', 'pantry',
  'parcel', 'pardon', 'parish', 'parody', 'parrot', 'patent', 'patron', 'pebble',
  'peddle', 'pester', 'pickle', 'pigeon', 'pillar', 'pillow', 'pincer', 'pounce',
  'powder', 'praise', 'preach', 'prefer', 'pretty', 'priest', 'prison', 'proper',
  'prosper', 'puddle', 'pursue', 'ragged', 'ramble', 'rankle', 'rattle', 'ravage',
  'reboot', 'recast', 'reckon', 'recoil', 'record', 'redeem', 'reduce', 'refine',
  'refuge', 'regime', 'rename', 'render', 'rescue', 'resent', 'retain', 'review',
  'revive', 'rhythm', 'riddle', 'rigged', 'ripple', 'robust', 'rotten', 'rugged',
  'rumble', 'rustle', 'scarce', 'scorch', 'scrape', 'scrawl', 'script', 'sealed',
  'sentry', 'settle', 'severed', 'shard', 'shrewd', 'shrink', 'shrimp', 'shroud',
  'signet', 'simmer', 'skewer', 'sketch', 'slogan', 'smudge', 'snatch', 'snobby',
  'soften', 'somber', 'sortie', 'splash', 'sprout', 'squall', 'squash', 'squeak',
  'starch', 'starve', 'stasis', 'statue', 'steady', 'stealth', 'stifle', 'stitch',
  'stomps', 'strain', 'stroll', 'strung', 'summit', 'sunken', 'surfer', 'swivel',
  'tangle', 'tailor', 'tactic', 'tangle', 'thatch', 'thrift', 'tickle', 'tingle',
  'toddle', 'toggle', 'touchy', 'toughen', 'trample', 'treble', 'tremor', 'tribal',
  'triple', 'trowel', 'trudge', 'twitch', 'tycoon', 'unclog', 'uncork', 'unfold',
  'unify', 'unruly', 'unveil', 'upbeat', 'uplift', 'uproot', 'uproar', 'vanish',
  'varnish', 'vaunt', 'vendor', 'verbal', 'vermin', 'vertex', 'vocals', 'voyage',
  'waddle', 'warden', 'waffle', 'warmth', 'wealth', 'weaken', 'weapon', 'weaver',
  'wedged', 'wiggle', 'wilful', 'wither', 'wizard', 'wobble', 'woe', 'wraith',
  'wreathe', 'writhe', 'zealot', 'zenith',
]

// All valid 6-letter guess words (superset of answer words — used for validation)
// For now, same as GANDLE_WORDS. Extend this list to allow more valid guesses.
export const GANDLE_VALID_GUESSES: ReadonlySet<string> = new Set(GANDLE_WORDS)
